
title: Cody the Coder
email: codyzeitler12@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is one of the best websites that has ever been created. 
  Don't believe me? Well read just one article, then you'll see I am right.
baseurl: "codythecoder" # the subpath of your site, e.g. /blog
url: "codythomaszeitler.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  codythomaszeitler

# Build settings
theme: minima
plugins:
  - jekyll-feed

lsi: false
safe: true
source: [/]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
