# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cody the Coder
email: codyzeitler12@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My name is Cody. I am a coder. I feel like I was born to do this. If you take a look at the syllables in my name, you will actually be able to see that code is a part of my name. Don't see it? Let's try it together. Code-ee. See it? That first part? If you don't you may need glasses, or maybe you need to learn to read. Somehow, I feel if you have gotten this far in the message, its the former, not the latter. Anyways, it is a part of me. I was born to code.
  This website it to facillate dynamic, non-dogmatic conversations about programming. Is TDD always the best option? Is there any other way to do GUI programming besides MVC? Is Java really all that slow? I hope this will be a place of learning and exploration of WHY we do the things that we do, and not to follow the newest trends blindly (no early returns anyone?). So I invite you to stay awhile and enjoy the articles and the code :)
  Also, I will ALWAYS include coding examples with my discussions, and I hope you will do the same. And for every conclusion A that I reach, I promise to always have detailed analysis of how I reached that conclusion.
  Stay awhile and please share! I want the best of the best to teach and for the noobies to learn!
  With each article there will be a passion level associated with it. This is how "fierce" I am into the contents of this article. They are listed as follows:
  All discussions listed below...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
